### ISSUE TITLE
Depreciation of VacuumEntity

### ISSUE THREAD

**Issue by ChrisThomas42** [jonnyrider/eufy_vacuum_15c#1]
Hi, with the depreciation of `VacuumEntity` being replaced with `StateVacuumEntity` the code need some updating.  My coding skills are not up to the task, although I can help as much as I can.

My quick look at the `vacuum.py` and simple replacement of `VacuumEntity` with `StateVacuumEntity` wasn't as successful as I first hoped.  I don't get any errors, but the state is always `unknown`, so I'm guessing there are other changes that I didn't see, or understand, in the documentation.

Chris

**Comment by jonnyrider** [comment]
Sorry, but I no longer use home assistant with my robovac, so I haven't updated the code! I wouldn't know where to look either, as I just copied this from someone else a long time ago!
